### ISSUE TITLE
Cannot find module 'poseidon-lite' when npx hardhat test  

### ISSUE THREAD

**Issue by Alexander-Herranz** [hyperledger-labs/zeto#115]
Node.JS installed (tried with both v20.18.1 and v22.12.0)

I previously tried both:

```
export ZETO_NAME=Zeto_AnonEncNullifier
npx hardhat run scripts/deploy_upgradeable.js
```

and

```
export ZETO_NAME=Zeto_AnonEncNullifier
npx hardhat run scripts/deploy_cloneable.js
```

And when trying to execute tests, in both cases I got the same error about 'poseidon-lite':

➜  solidity git:(main) npx hardhat test                               
An unexpected error occurred:

Error: Cannot find module 'poseidon-lite'
Require stack:
- /Users/alexander//zeto-lab/zeto/zkp/js/index.js
- /Users/alexander//zeto-lab/zeto/solidity/test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts
- /Users/alexander/zeto-lab/zeto/solidity/node_modules/mocha/lib/mocha.js
- /Users/alexander/zeto-lab/zeto/solidity/node_modules/mocha/index.js
- /Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/builtin-tasks/test.js
- /Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/core/tasks/builtin-tasks.js
- /Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/core/config/config-loading.js
- /Users/Alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/cli/cli.js
- /Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/cli/bootstrap.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1249:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/alexander/zeto-lab/zeto/solidity/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function._load (node:internal/modules/cjs/loader:1075:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24)
    at Module.require (node:internal/modules/cjs/loader:1340:12)
    at require (node:internal/modules/helpers:138:16)
    at Object.<anonymous> (/Users/alexander/Documents/Alexander/zeto-lab/zeto/zkp/js/index.js:19:18)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at node:internal/modules/cjs/loader:1708:10 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/alexander/zeto-lab/zeto/zkp/js/index.js',
    '/Users/alexander/Documents/Alexander/zeto-lab/zeto/solidity/test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/mocha/lib/mocha.js',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/mocha/index.js',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/builtin-tasks/test.js',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/core/tasks/builtin-tasks.js',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/core/config/config-loading.js',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/cli/cli.js',
    '/Users/alexander/zeto-lab/zeto/solidity/node_modules/hardhat/internal/cli/bootstrap.js'
  ]

**Comment by Chengxuan** [comment]
@Alexander-Herranz the solidity test uses utility functions in `zkp/js` folder. Please ensure you've run `npm i` under that directory. 

Please feel free to update the readme if that step is missing.
