### ISSUE TITLE
`Invalid proof` when generating proofs concurrently in Zeto test

### ISSUE THREAD

**Issue by Chengxuan** [hyperledger-labs/zeto#80]
Example error log when running the test with [2 thread running in parallel](https://github.com/hyperledger-labs/zeto/blob/544659ea388d512b02f556ac7ee9b7ee608ddc9e/solidity/test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts#L316):
```
  1) (Gas cost analysis) Zeto based fungible token with anonymity using nullifiers and encryption with KYC
       Transfer 20 tokens (half from deposit, half from mint) from single address to another
         Alice transfer 20 tokens to Bob in 10 txs:
     Error: VM Exception while processing transaction: reverted with reason string 'Invalid proof'
    at Zeto_AnonEncNullifierKyc.transfer (contracts/zeto_anon_enc_nullifier_kyc.sol:111)
    at <UnrecognizedContract>.<unknown> (0x2279b7a0a67db372996a5fab50d91eaa73d2ebe6)
    at EdrProviderWrapper.request (node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:431:41)
    at async HardhatEthersSigner.sendTransaction (node_modules/@nomicfoundation/hardhat-ethers/src/signers.ts:125:18)
    at async send (node_modules/ethers/src.ts/contract/contract.ts:313:20)
    at async Proxy.transfer (node_modules/ethers/src.ts/contract/contract.ts:352:16)
    at async sendTx (test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts:557:16)
    at async doTransfer (test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts:452:22)
    at async /Users/cxing/go/src/github.com/hyperledger-labs/zeto/solidity/test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts:362:13
    at async Promise.all (index 6)
    at async Context.<anonymous> (test/gas_cost/zeto_anon_enc_nullifier_kyc_cost_analysis.ts:388:9)
```

**Comment by Chengxuan** [comment]
The issue is related to concurrently generating witness, added a lock as a workaround https://github.com/hyperledger-labs/zeto/pull/79/files#diff-d9c87e662d919b1fda426b303d12170fd15f677870092c06e8c3062aa8eae21bR518 .

 need more debug to figure out what's special of the transfer circuit

**Comment by Chengxuan** [comment]
Closing this issue as it's addressed by https://github.com/iden3/circom/pull/299

**Comment by Chengxuan** [comment]
I also found `generateCircomVerifierProof` needed a lock as well. this could be another bug that isn't covered by the circom PR different bug
